"""Stage a per-device IoT Gateway credential for every Bunty upload.

The credential is generated by iot-gateway's device CLI, stored remotely in
Cloudflare D1 as a hash, and written only to Bunty's ignored .pio directory.
After a successful upload, the staged credential is promoted and the previous
credential is retired. A failed upload leaves the previous credential valid.
"""

import os
from pathlib import Path
import re
import shutil
import subprocess

Import("env")
from SCons.Script import COMMAND_LINE_TARGETS, Exit

if env.IsIntegrationDump():
    Return()

DEVICE_ID = "bunty"
TOKEN_PATTERN = re.compile(r"^iot_[A-Za-z0-9_-]{43}$")
PROJECT_DIR = Path(env.subst("$PROJECT_DIR")).resolve()
REPOSITORY_ROOT = PROJECT_DIR.parent.parent
GATEWAY_DIR = REPOSITORY_ROOT / "iot-gateway"
DEVICE_SCRIPT = GATEWAY_DIR / "scripts" / "devices.mjs"
GENERATED_DIR = PROJECT_DIR / ".pio" / "generated"
CREDENTIAL_HEADER = GENERATED_DIR / "IotGatewayCredentials.generated.h"
ACTIVATION_MARKER = GENERATED_DIR / "iot_gateway_activation_pending"

env.Append(CPPPATH=[str(GENERATED_DIR)])


def gateway_command(action, token_only=False):
    node = shutil.which("node")
    if not node:
        raise RuntimeError("Node.js is required to provision the IoT Gateway credential")
    if not DEVICE_SCRIPT.is_file():
        raise RuntimeError(
            f"IoT Gateway device script not found at {DEVICE_SCRIPT}. "
            "Keep iot-gateway at the repository root."
        )

    command = [
        node,
        str(DEVICE_SCRIPT),
        action,
        DEVICE_ID,
        "--remote",
    ]
    if token_only:
        command.append("--token-only")

    result = subprocess.run(
        command,
        cwd=GATEWAY_DIR,
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
        env={**os.environ, "NO_COLOR": "1"},
    )
    if result.returncode != 0:
        details = "\n".join(
            part.strip() for part in (result.stdout, result.stderr) if part.strip()
        )
        raise RuntimeError(
            f"IoT Gateway '{action}' failed.\n{details}" if details else
            f"IoT Gateway '{action}' failed with exit code {result.returncode}."
        )
    return result.stdout.strip()


def write_credential_header(token):
    if token and not TOKEN_PATTERN.fullmatch(token):
        raise RuntimeError("IoT Gateway returned an invalid device token")

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    temporary_header = CREDENTIAL_HEADER.with_suffix(".tmp")
    temporary_header.write_text(
        "#pragma once\n"
        f'#define IOT_GATEWAY_DEVICE_ID "{DEVICE_ID}"\n'
        f'#define IOT_GATEWAY_TOKEN "{token}"\n',
        encoding="utf-8",
    )
    try:
        temporary_header.chmod(0o600)
    except OSError:
        pass
    temporary_header.replace(CREDENTIAL_HEADER)


upload_requested = "upload" in COMMAND_LINE_TARGETS
provision_requested = upload_requested and os.environ.get(
    "BUNTY_PROVISION_IOT", ""
).strip().lower() in {"1", "true", "yes", "on"}

if provision_requested:
    try:
        if ACTIVATION_MARKER.exists():
            gateway_command("activate")
            ACTIVATION_MARKER.unlink(missing_ok=True)
            print("[iot-gateway] completed activation from the previous flash")
        staged_token = gateway_command("stage", token_only=True)
        write_credential_header(staged_token)
        print(
            "[iot-gateway] staged a new credential for bunty in the ignored build directory"
        )
    except (OSError, subprocess.SubprocessError, RuntimeError) as error:
        print(f"[iot-gateway] {error}")
        Exit(1)
elif not CREDENTIAL_HEADER.exists():
    # Ordinary builds and uploads remain possible before provisioning. An
    # explicitly provisioned upload replaces this empty fallback before build.
    write_credential_header("")


def activate_after_upload(source, target, construction_env):
    try:
        ACTIVATION_MARKER.write_text("bunty\n", encoding="utf-8")
        gateway_command("activate")
        ACTIVATION_MARKER.unlink(missing_ok=True)
        print("[iot-gateway] activated bunty's flashed credential")
    except (OSError, subprocess.SubprocessError, RuntimeError) as error:
        # The staged token remains accepted by the Worker, so the freshly
        # flashed device is not locked out. The marker makes the next upload
        # retry activation before it stages another token.
        print(f"[iot-gateway] upload succeeded, but activation failed: {error}")
        print(
            "[iot-gateway] retry with: "
            "cd ../../iot-gateway && npm run device -- activate bunty --remote"
        )
        raise


if provision_requested:
    env.AddPostAction("upload", activate_after_upload)
